NAME: 'reproducing'

DATASET:
    TRAINDIR_ATR : 'data/Train/ATR/Image'
    MAPDIR_ATR :  'data/Train/ATR/Parsing'
    TEST : 'data/Test'
    TRAINDIR_LIP : 'data/Train/LIP/Image'
    MAPDIR_LIP : 'data/Train/LIP/Parsing'
    INPUT_RES: 256
    LOCAL_RES: 128
    HOLE_MIN: 64
    HOLE_MAX: 127
    MEAN: [0.4560,  0.4472,  0.4155]

LOSS:
  ALPHA: 0.0004

TRAIN_G_EVERY: 1
TRAIN_D_EVERY: 1

IS_TRAIN: True
TOTAL_EPOCHES_ATR : 200
TOTAL_EPOCHES_LIP: 100
INIT: '/home/lrl/Siggraph2018/glcic/src/completionnet_places2.t7'

SOLVER:
  WORKERS: 0
  IMG_PER_GPU: 16
  GPU_IDS: [0] # real BATCHSIZE is : IMG_PER_GPU * len(GPU_IDS) 
  LR: 0.0002
  LR_SCHEDULE: 'standard'
  OPTIMIZER: 'ADAM' # ADAM | SGD
  MOMENTUM: 0.9
  WEIGHTDECAY: 0.0004
  LAMBDA_P: 100
  LAMBDA_G: 1
  LAMBDA_L: 1
LOGS:
  PRINT_FREQ: 1
  SNAPSHOT_FREQ: 1
  SNAPSHOT_MAXFILES: NOTIMPLEMENT
  SNAPSHOT_DIR: 'snapshot'
  LOG_FREQ: 1
  LOG_DIR: 'logs'
  LOG_SHUTIL_ON: true
  # shutil.copytree('./', './logs2', ignore=shutil.ignore_patterns('./logs','*.zip','*.mp4','*.jpg','*.png','__pycache__', '*.pyc'))
  LOG_SHUTIL_IGNORELIST: ['*.zip','*.mp4','*.jpg','*.png','*.pyc','*.so','*.pkl','*.caffemodel', '__pycache__','snapshot','logs']
  LOG_SHUTIL_IGNOREFILE: '.gitignore'
  
